# Uncomment the next line to define a global platform for your project
# platform :ios, ‘7.0’

target 'RWReactivePlayground' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RWReactivePlayground

pod ‘ReactiveCocoa’, ‘2.1.8’

  target 'RWReactivePlaygroundTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
