# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'RAC01' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

	pod 'ReactiveObjC'

  # Pods for RAC01

  target 'RAC01UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
